// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbBNvl2lbSeZWvNAP84ugfiZ8mj_Tazc',
    appId: '1:1034471241738:web:4c6feb8592d932066487f3',
    messagingSenderId: '1034471241738',
    projectId: 'bestkit-2dc0b',
    authDomain: 'bestkit-2dc0b.firebaseapp.com',
    storageBucket: 'bestkit-2dc0b.firebasestorage.app',
    measurementId: 'G-VDG52YP6D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTcza04jakvmY_bZzQpqnToKH-aWYCEh8',
    appId: '1:1034471241738:android:87da7efbadf85b406487f3',
    messagingSenderId: '1034471241738',
    projectId: 'bestkit-2dc0b',
    storageBucket: 'bestkit-2dc0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUt6sBiXh0lQR_nIce7YQ18QrEb97rbBg',
    appId: '1:1034471241738:ios:8debfb7d25feea146487f3',
    messagingSenderId: '1034471241738',
    projectId: 'bestkit-2dc0b',
    storageBucket: 'bestkit-2dc0b.firebasestorage.app',
    iosBundleId: 'com.lwm.bestkits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUt6sBiXh0lQR_nIce7YQ18QrEb97rbBg',
    appId: '1:1034471241738:ios:8debfb7d25feea146487f3',
    messagingSenderId: '1034471241738',
    projectId: 'bestkit-2dc0b',
    storageBucket: 'bestkit-2dc0b.firebasestorage.app',
    iosBundleId: 'com.lwm.bestkits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrbBNvl2lbSeZWvNAP84ugfiZ8mj_Tazc',
    appId: '1:1034471241738:web:4b088987bf8b6ca96487f3',
    messagingSenderId: '1034471241738',
    projectId: 'bestkit-2dc0b',
    authDomain: 'bestkit-2dc0b.firebaseapp.com',
    storageBucket: 'bestkit-2dc0b.firebasestorage.app',
    measurementId: 'G-HNSTT2EYKV',
  );
}
